language: node_js
node_js:
    - "6"
install:
    - npm install -g grunt-cli
    - npm install
script:
    - grunt release
    - npm test
deploy:
    name: PINT WebApp
    provider: pages
    local_dir: build
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
