language: node_js
node_js:
- '6'
install:
- npm install -g grunt-cli
- npm install
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgif-dev
script:
- grunt release
- npm test
deploy:
  - provider: heroku
    api_key:
      secure: CKBBuPLym4TZOqvTBrQLltyZh020ImS7YbSoLR+D9YA5S2MDeq1YbJXLlWm+y8+PdvvgDG/ezJqlJqXtlr9iTrjmA9zpqcsZjlvzgzpWJSFsGPa5H9PbQBaXKcqSXnJTYZtT5/wY79Pe+pSClQG6AeRrRA3c5i4u8MfyH7W/78Kg79lwlLGr59zsA2Cc4tJS3oDXFVxGyTF4/endnpwB2axCOE/+lEac1nITwpzThj4TaiMPhFZ7/DP7hzQhzXm8h3UlJQJLPpThmCB587BaO5ZcjrQYTqSwiHoEaj1TqvaPV7Zchyv9M2uFc8uU2S7RL4MfBvGQp+JI3/54454TqpR0D3Fj3s8ZKL3KWVnbA9tFMqG37LtLoXpO4zoAZpt4Xnf/AmPJYuN+4odXqzg1J3thaR74Y+ykJ5YLgy875m8+z9pLRCgQt7N90WFbGxr14ZDA8VR9Qbgqe8nJD+goorQhrmeZHR/h993075XEaORUBDAqcvyjHzEV2V8/LlkBn/Jil1pp0I16qV32C9JF7QPZEVQWnE/EyPnBI20S91ZibtU/g5LQK6CTuIuywwqRg/Fa9OxLXmDGgLmUaId4QGxRHu/5Ihcj6kALOLAQ4BsZOvB0uBcIm2Dhj/ox7Fzjie2uot1LrwELDZ7+xLYgpmB6t+8cEr4i8yrIGTTHmhs=
    app: pintjs
    skip_cleanup: true
    local_dir: build
    on:
      repo: VengeurK/PINT
      branch: master
  - provider: pages
    name: PINT WebApp
    local_dir: build
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
