/**
 * This function thinks a lot and do good work.
 * @returns {number} the answer to life, the universe and everything
 */
function giveMeTheAnswer() {
    return 42;
}

/**
 * The true answer to every question.
 *
 * @param {Object} oui oeifdzio
 * @returns {number} a random number generated by the random number generator
 */
function giveMeANumberBetweenZeroAndOne() {
    return Math.random();
}